namespace Durable.LiteDb
{
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Text;
    using Durable;
    using LiteDB;

    /// <summary>
    /// How an entity is stored in a LiteDB collection: the collection is <see cref="EntityMetadata.TableName"/>; each
    /// column is a document field named after the column, except a single primary key, which is stored as the document
    /// <c>_id</c>; a composite key is stored both as its fields and as an <c>_id</c> sub-document holding the key parts in
    /// key order. Auto-increment is supported for a single integral primary key (generated by LiteDB's per-collection
    /// sequence). Also lists the fields that get secondary indexes: foreign keys, composite key parts and
    /// <see cref="IndexAttribute"/> columns whose values are bounded (non-string types, or strings with a
    /// <see cref="ColumnMetadata.MaxLength"/> of at most <see cref="MaxIndexedStringLength"/>).
    /// Thread safety: immutable once built; <see cref="For"/> is thread-safe.
    /// </summary>
    internal sealed class LiteDbCollectionSchema
    {
        #region Public-Members

        /// <summary>
        /// The document field holding the primary key.
        /// </summary>
        public const string IdField = "_id";

        /// <summary>
        /// The longest string column (in characters) that gets a secondary index; LiteDB index keys are limited to 1023 bytes.
        /// </summary>
        public const int MaxIndexedStringLength = 250;

        /// <summary>
        /// Gets the entity metadata. Never null.
        /// </summary>
        public EntityMetadata Metadata { get; }

        /// <summary>
        /// Gets the collection name. Never null.
        /// </summary>
        public string CollectionName { get; }

        /// <summary>
        /// Gets whether the key is stored as the document <c>_id</c> directly (a single key column).
        /// </summary>
        public bool SingleKey { get; }

        /// <summary>
        /// Gets the LiteDB auto-id mode for generated keys, or null when the entity has no auto-increment column.
        /// </summary>
        public BsonAutoId? AutoId { get; }

        /// <summary>
        /// Gets the columns that get secondary indexes, with their index names. Never null.
        /// </summary>
        public IReadOnlyList<KeyValuePair<ColumnMetadata, string>> IndexedColumns { get; }

        #endregion

        #region Private-Members

        private static readonly ConcurrentDictionary<Type, LiteDbCollectionSchema> _Cache = new ConcurrentDictionary<Type, LiteDbCollectionSchema>();
        private readonly Dictionary<ColumnMetadata, string> _Fields = new Dictionary<ColumnMetadata, string>(ReferenceEqualityComparer.Instance);
        private readonly Dictionary<string, string> _FieldsByProperty = new Dictionary<string, string>(StringComparer.Ordinal);
        private readonly Dictionary<ColumnMetadata, Type> _StoredTypes = new Dictionary<ColumnMetadata, Type>(ReferenceEqualityComparer.Instance);

        #endregion

        #region Constructors-and-Factories

        private LiteDbCollectionSchema(EntityMetadata metadata)
        {
            Metadata = metadata;
            CollectionName = metadata.TableName;
            ValidateCollectionName(metadata);
            metadata.RequireKey();
            SingleKey = metadata.KeyColumns.Count == 1;

            HashSet<string> seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (ColumnMetadata column in metadata.Columns)
            {
                string field = SingleKey && column.IsPrimaryKey ? IdField : column.Name;
                if (string.Equals(column.Name, IdField, StringComparison.OrdinalIgnoreCase) && !(SingleKey && column.IsPrimaryKey))
                    throw new NotSupportedException("Column '" + column.Name + "' of " + metadata.EntityType.Name + " is reserved by LiteDB for the primary key; only a single primary key column may be named '_id'.");
                if (!seen.Add(field))
                    throw new NotSupportedException("Columns of " + metadata.EntityType.Name + " map to the same LiteDB field '" + field + "' (LiteDB field names are case-insensitive).");
                _Fields[column] = field;
                _FieldsByProperty[column.Property.Name] = field;
                _StoredTypes[column] = LiteDbValueConverter.StoredType(column);
            }

            ColumnMetadata? generated = metadata.AutoIncrementColumn;
            if (generated != null)
            {
                Type stored = _StoredTypes[generated];
                if (!SingleKey || !generated.IsPrimaryKey)
                    throw new NotSupportedException("The LiteDB backend generates auto-increment values only for a single primary key column; " + metadata.EntityType.Name + "." + generated.Property.Name + " is not one.");
                if (stored == typeof(long) || stored == typeof(uint)) AutoId = BsonAutoId.Int64;
                else if (stored == typeof(int) || stored == typeof(short) || stored == typeof(byte) || stored == typeof(ushort) || stored == typeof(sbyte)) AutoId = BsonAutoId.Int32;
                else throw new NotSupportedException("The LiteDB backend generates auto-increment values only for integer keys; " + metadata.EntityType.Name + "." + generated.Property.Name + " is " + stored.Name + ".");
            }

            List<KeyValuePair<ColumnMetadata, string>> indexed = new List<KeyValuePair<ColumnMetadata, string>>();
            HashSet<string> indexNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (ColumnMetadata column in metadata.Columns)
            {
                if (_Fields[column] == IdField) continue;
                bool wanted = column.ForeignKey != null || column.Indexes.Count > 0 || (column.IsPrimaryKey && !SingleKey);
                if (!wanted || !IsBounded(column)) continue;
                string name = IndexName(column.Name);
                if (indexNames.Add(name)) indexed.Add(new KeyValuePair<ColumnMetadata, string>(column, name));
            }

            IndexedColumns = indexed;
        }

        /// <summary>
        /// Returns the cached schema of an entity.
        /// </summary>
        /// <param name="metadata">Entity metadata. Must not be null.</param>
        /// <returns>The schema.</returns>
        /// <exception cref="ArgumentNullException">Thrown when metadata is null.</exception>
        /// <exception cref="NotSupportedException">Thrown when the entity cannot be stored in LiteDB (invalid collection name, reserved or colliding field names, unsupported auto-increment).</exception>
        public static LiteDbCollectionSchema For(EntityMetadata metadata)
        {
            ArgumentNullException.ThrowIfNull(metadata);
            if (_Cache.TryGetValue(metadata.EntityType, out LiteDbCollectionSchema? cached)) return cached;
            LiteDbCollectionSchema schema = new LiteDbCollectionSchema(metadata);
            return _Cache.GetOrAdd(metadata.EntityType, schema);
        }

        #endregion

        #region Public-Methods

        /// <summary>
        /// Returns the document field of a column.
        /// </summary>
        /// <param name="column">Column of this entity. Must not be null.</param>
        /// <returns>The field name.</returns>
        /// <exception cref="InvalidOperationException">Thrown when the column does not belong to the entity.</exception>
        public string Field(ColumnMetadata column)
        {
            if (_Fields.TryGetValue(column, out string? field)) return field;
            if (_FieldsByProperty.TryGetValue(column.Property.Name, out field)) return field;
            throw new InvalidOperationException("Column '" + column.Name + "' is not mapped by " + Metadata.EntityType.Name + ".");
        }

        /// <summary>
        /// Returns the stored type of a column (see <see cref="LiteDbValueConverter.StoredType"/>).
        /// </summary>
        /// <param name="column">Column. Must not be null.</param>
        /// <returns>The stored type.</returns>
        public Type StoredType(ColumnMetadata column)
        {
            return _StoredTypes.TryGetValue(column, out Type? type) ? type : LiteDbValueConverter.StoredType(column);
        }

        /// <summary>
        /// Returns the LiteDB path expression of a column's field, for example <c>$.["name"]</c>.
        /// </summary>
        /// <param name="column">Column. Must not be null.</param>
        /// <returns>The path expression.</returns>
        public string Path(ColumnMetadata column)
        {
            return FieldPath(Field(column));
        }

        /// <summary>
        /// Returns the LiteDB path expression of a field.
        /// </summary>
        /// <param name="field">Field name. Must not be null.</param>
        /// <returns>The path expression.</returns>
        public static string FieldPath(string field)
        {
            if (field == IdField) return "$._id";
            StringBuilder path = new StringBuilder("$.[\"", field.Length + 8);
            foreach (char c in field)
            {
                switch (c)
                {
                    case '"': path.Append("\\\""); break;
                    case '\\': path.Append("\\\\"); break;
                    case '\n': path.Append("\\n"); break;
                    case '\r': path.Append("\\r"); break;
                    case '\t': path.Append("\\t"); break;
                    default:
                        if (c < ' ') path.Append("\\u").Append(((int)c).ToString("x4", CultureInfo.InvariantCulture));
                        else path.Append(c);
                        break;
                }
            }

            return path.Append("\"]").ToString();
        }

        /// <summary>
        /// Builds the document <c>_id</c> of a key.
        /// </summary>
        /// <param name="storedKey">Stored key values in key order. Must not be null; no part may be null.</param>
        /// <returns>The _id value.</returns>
        /// <exception cref="InvalidOperationException">Thrown when a key part is null.</exception>
        public BsonValue Id(object?[] storedKey)
        {
            for (int i = 0; i < storedKey.Length; i++)
            {
                if (storedKey[i] == null)
                    throw new InvalidOperationException("Primary key column '" + Metadata.KeyColumns[i].Name + "' of " + Metadata.EntityType.Name + " is null.");
            }

            if (SingleKey) return LiteDbBsonCodec.Encode(storedKey[0]);
            BsonDocument id = new BsonDocument();
            for (int i = 0; i < storedKey.Length; i++) id[Metadata.KeyColumns[i].Name] = LiteDbBsonCodec.Encode(storedKey[i]);
            return id;
        }

        #endregion

        #region Private-Methods

        private static void ValidateCollectionName(EntityMetadata metadata)
        {
            string name = metadata.TableName;
            bool valid = name.Length > 0 && !name.StartsWith("$", StringComparison.Ordinal);
            for (int i = 0; valid && i < name.Length; i++) valid = IsWordChar(name[i], i == 0);
            if (!valid)
                throw new NotSupportedException("Table name '" + name + "' of " + metadata.EntityType.Name + " is not a valid LiteDB collection name (letters, digits, '_' and '$', not starting with a digit or '$').");
        }

        private bool IsBounded(ColumnMetadata column)
        {
            Type stored = _StoredTypes[column];
            if (stored == typeof(byte[])) return false;
            if (stored == typeof(string)) return column.MaxLength > 0 && column.MaxLength <= MaxIndexedStringLength && column.Converter == null && !column.IsJson;
            return true;
        }

        private static string IndexName(string column)
        {
            StringBuilder name = new StringBuilder("ix_");
            bool changed = false;
            foreach (char c in column)
            {
                if (IsWordChar(c, false) && c != '$') name.Append(c);
                else
                {
                    name.Append('_');
                    changed = true;
                }
            }

            if (!changed && name.Length <= 32) return name.ToString();
            uint hash = 2166136261;
            foreach (char c in column) hash = unchecked((hash ^ c) * 16777619);
            string suffix = "_" + hash.ToString("x8", CultureInfo.InvariantCulture);
            string prefix = name.ToString();
            if (prefix.Length > 32 - suffix.Length) prefix = prefix.Substring(0, 32 - suffix.Length);
            return prefix + suffix;
        }

        private static bool IsWordChar(char c, bool first)
        {
            if (first) return char.IsLetter(c) || c == '_' || c == '$';
            return char.IsLetterOrDigit(c) || c == '_' || c == '$';
        }

        #endregion
    }
}
