namespace Durable.DefaultValueProviders
{
    using System;
    using System.Reflection;

    /// <summary>
    /// Provides a default value generated by a delegate function
    /// Thread safety: as thread-safe as the supplied factory delegate.
    /// </summary>
    public class DelegateValueProvider : IDefaultValueProvider
    {
        private readonly Func<object?> _ValueFactory;
        private readonly bool _OnlyIfNull;

        /// <summary>
        /// Initializes a new instance of the DelegateValueProvider class
        /// </summary>
        /// <param name="valueFactory">Function that generates the default value</param>
        /// <param name="onlyIfNull">If true, only apply when the current value is null/default</param>
        public DelegateValueProvider(Func<object?> valueFactory, bool onlyIfNull = true)
        {
            _ValueFactory = valueFactory ?? throw new ArgumentNullException(nameof(valueFactory));
            _OnlyIfNull = onlyIfNull;
        }

        /// <inheritdoc/>
        public object? GetDefaultValue(PropertyInfo property, object entity)
        {
            return _ValueFactory();
        }

        /// <inheritdoc/>
        public bool ShouldApply(object? currentValue, Type propertyType)
        {
            if (!_OnlyIfNull) return true;
            if (currentValue == null) return true;

            // Check if value is the default for its type
            if (propertyType.IsValueType)
            {
                object defaultValue = MemberAccessorFactory.GetDefaultValue(propertyType)!;
                return currentValue.Equals(defaultValue);
            }

            return false;
        }
    }
}
