<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<OutputType>Exe</OutputType>
		<IsPackable>false</IsPackable>
		<Nullable>enable</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>
		<NoWarn>$(NoWarn);CS1591</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
		<PackageReference Include="Dapper" Version="2.1.66" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Durable.Sqlite\Durable.Sqlite.csproj" />
		<ProjectReference Include="..\Durable.Postgres\Durable.Postgres.csproj" />
	</ItemGroup>

</Project>
