namespace Durable.Tool
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Linq;
    using Durable.Sql;

    /// <summary>
    /// Generates a Durable entity class (<c>[Entity]</c>, <c>[Property]</c> with flags and maximum lengths, nullable types,
    /// <c>[Index]</c> and <c>[CompositeIndex]</c>) from a table read by <see cref="DatabaseSchemaReader"/>. The generated code
    /// follows the repository style: usings inside the namespace, explicit types and XML documentation on public members.
    /// It assumes nullable reference types are enabled.
    /// </summary>
    internal static class EntityCodeGenerator
    {
        /// <summary>
        /// Generates the source of one entity class.
        /// </summary>
        /// <param name="dialect">Dialect of the database. Must not be null.</param>
        /// <param name="table">Table. Must not be null.</param>
        /// <param name="namespaceName">Namespace. Must not be null.</param>
        /// <param name="className">Class name. Must not be null.</param>
        /// <returns>The C# source.</returns>
        public static string Generate(ISqlDialect dialect, TableSchema table, string namespaceName, string className)
        {
            ArgumentNullException.ThrowIfNull(dialect);
            ArgumentNullException.ThrowIfNull(table);
            ArgumentNullException.ThrowIfNull(namespaceName);
            ArgumentNullException.ThrowIfNull(className);

            HashSet<string> usedNames = new HashSet<string>(StringComparer.Ordinal) { className };
            Dictionary<string, string> propertyNames = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            foreach (ColumnSchema column in table.Columns)
            {
                string preferred = CSharpNames.ToPascalCase(column.Name, "Column");
                if (preferred == className) preferred += "Value";
                propertyNames[column.Name] = CSharpNames.MakeUnique(preferred, usedNames);
            }

            List<string> keyColumns = table.PrimaryKeyColumns.ToList();
            List<IndexSchema> singleIndexes = table.Indexes.Where(i => i.Columns.Count == 1).ToList();
            List<IndexSchema> compositeIndexes = table.Indexes.Where(i => i.Columns.Count > 1).ToList();

            CodeWriter code = new CodeWriter();
            code.Line("namespace " + namespaceName).Open();
            code.Line("using System;");
            code.Line("using Durable;");
            code.Blank();
            code.Summary(
                "Entity mapped to the <c>" + CSharpNames.XmlEscape(table.Name) + "</c> table. Generated by <c>durable scaffold</c> from the " +
                CSharpNames.XmlEscape(dialect.RepositoryType.DisplayName) + " schema.");
            if (keyColumns.Count == 0)
                code.Line("// WARNING: the table has no primary key, which Durable requires. Mark the key property with Flags.PrimaryKey.");
            code.Line("[Entity(" + CSharpNames.StringLiteral(table.Name) + ")]");
            foreach (IndexSchema index in compositeIndexes)
            {
                List<string> parts = new List<string> { CSharpNames.StringLiteral(index.Name) };
                parts.AddRange(index.Columns.Select(CSharpNames.StringLiteral));
                if (index.IsUnique) parts.Add("IsUnique = true");
                if (index.IncludedColumns.Count > 0) parts.Add("IncludedColumns = " + ArrayLiteral(index.IncludedColumns));
                code.Line("[CompositeIndex(" + string.Join(", ", parts) + ")]");
            }

            code.Line("public class " + className).Open();
            bool first = true;
            foreach (ColumnSchema column in table.Columns)
            {
                if (!first) code.Blank();
                first = false;
                WriteProperty(code, dialect, column, propertyNames[column.Name], keyColumns, singleIndexes);
            }

            code.Close();
            code.Close();
            return code.ToString();
        }

        private static void WriteProperty(CodeWriter code, ISqlDialect dialect, ColumnSchema column, string propertyName, List<string> keyColumns, List<IndexSchema> singleIndexes)
        {
            ScaffoldColumnType type = ClrTypeMapper.Map(dialect, column);
            bool isKey = column.IsPrimaryKey;
            bool nullable = column.IsNullable && !isKey;

            List<string> details = new List<string> { column.DataType.Trim() };
            details.Add(nullable ? "nullable" : "not null");
            if (isKey) details.Add(column.IsAutoIncrement ? "primary key, generated by the database" : "primary key");
            code.Summary("Gets or sets the <c>" + CSharpNames.XmlEscape(column.Name) + "</c> column (" + CSharpNames.XmlEscape(string.Join(", ", details)) + ").");
            if (type.Note != null) code.Line("// " + type.Note);

            List<string> flags = new List<string>();
            if (isKey) flags.Add("Flags.PrimaryKey");
            if (column.IsAutoIncrement) flags.Add("Flags.AutoIncrement");
            if (type.IsText) flags.Add("Flags.String");

            List<string> arguments = new List<string> { CSharpNames.StringLiteral(column.Name) };
            bool hasLength = type.IsText && column.MaxLength.HasValue && column.MaxLength.Value > 0;
            if (flags.Count > 0 || hasLength) arguments.Add(flags.Count > 0 ? string.Join(" | ", flags) : "Flags.None");
            if (hasLength) arguments.Add(column.MaxLength!.Value.ToString(CultureInfo.InvariantCulture));
            if (isKey && keyColumns.Count > 1)
                arguments.Add("KeyOrder = " + keyColumns.FindIndex(k => string.Equals(k, column.Name, StringComparison.OrdinalIgnoreCase)).ToString(CultureInfo.InvariantCulture));
            code.Line("[Property(" + string.Join(", ", arguments) + ")]");

            foreach (IndexSchema index in singleIndexes.Where(i => string.Equals(i.Columns[0], column.Name, StringComparison.OrdinalIgnoreCase)))
            {
                List<string> parts = new List<string> { CSharpNames.StringLiteral(index.Name) };
                if (index.IsUnique) parts.Add("true");
                if (index.IncludedColumns.Count > 0) parts.Add("IncludedColumns = " + ArrayLiteral(index.IncludedColumns));
                code.Line("[Index(" + string.Join(", ", parts) + ")]");
            }

            string declaration = "public " + type.TypeName + (nullable ? "?" : string.Empty) + " " + propertyName + " { get; set; }";
            if (type.IsReferenceType && !nullable && type.Initializer != null) declaration += " = " + type.Initializer + ";";
            code.Line(declaration);
        }

        private static string ArrayLiteral(IEnumerable<string> values)
        {
            return "new[] { " + string.Join(", ", values.Select(CSharpNames.StringLiteral)) + " }";
        }
    }
}
