namespace Durable.Tool
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Durable;
    using Durable.Sql;

    /// <summary>
    /// Generates <see cref="Migration"/> classes: an empty template, or one whose Up applies a <see cref="SchemaDiff"/> and
    /// whose Down reverses it when every applied operation is reversible. Generated code follows the repository style.
    /// </summary>
    internal static class MigrationCodeGenerator
    {
        /// <summary>
        /// Generates an empty migration.
        /// </summary>
        /// <param name="namespaceName">Namespace. Must not be null.</param>
        /// <param name="className">Class name. Must not be null.</param>
        /// <param name="id">Migration Id. Must not be null.</param>
        /// <returns>The C# source.</returns>
        public static string GenerateEmpty(string namespaceName, string className, string id)
        {
            CodeWriter code = Begin(namespaceName, className, id, "Migration " + className + ". Generated by <c>durable migrations add</c>.", false);
            code.Summary("Applies the migration.");
            code.Line("/// <param name=\"context\">Migration context.</param>");
            code.Line("public override void Up(MigrationContext context)").Open();
            code.Line("// Write the changes of this migration, for example:");
            code.Line("// context.ExecuteSqlRaw(\"ALTER TABLE users ADD COLUMN email VARCHAR(128) NULL\");");
            code.Line("// context.EnsureSchema(typeof(User));");
            code.Close();
            code.Blank();
            code.Line("// Override Down(MigrationContext) to make this migration reversible with 'durable rollback'.");
            return End(code);
        }

        /// <summary>
        /// Generates a migration applying a schema diff.
        /// </summary>
        /// <param name="namespaceName">Namespace. Must not be null.</param>
        /// <param name="className">Class name. Must not be null.</param>
        /// <param name="id">Migration Id. Must not be null.</param>
        /// <param name="diff">Diff between the entity types and the database. Must not be null.</param>
        /// <param name="includeDestructive">Whether destructive operations are applied (otherwise they become comments).</param>
        /// <returns>The C# source.</returns>
        public static string GenerateFromDiff(string namespaceName, string className, string id, SchemaDiff diff, bool includeDestructive)
        {
            ArgumentNullException.ThrowIfNull(diff);
            ISqlDialect dialect = diff.Dialect;
            List<MigrationOperation> included = diff.Operations.Where(o => includeDestructive || !o.IsDestructive).ToList();
            List<MigrationOperation> skipped = diff.Operations.Where(o => !includeDestructive && o.IsDestructive).ToList();
            List<MigrationOperation> irreversible = included.Where(o => Reverse(dialect, o) == null).ToList();
            bool hasDown = included.Count > 0 && irreversible.Count == 0;
            string databaseName = dialect.RepositoryType.DisplayName;

            CodeWriter code = Begin(
                namespaceName, className, id,
                "Migration " + className + ". Generated by <c>durable migrations add</c> from the differences between the entity types and the " +
                CSharpNames.XmlEscape(databaseName) + " database; the SQL is specific to " + CSharpNames.XmlEscape(databaseName) + ".",
                included.Count > 0);

            code.Summary("Applies the migration.");
            code.Line("/// <param name=\"context\">Migration context.</param>");
            if (included.Count > 0) code.Line("/// <exception cref=\"NotSupportedException\">Thrown when the database is not " + CSharpNames.XmlEscape(databaseName) + ".</exception>");
            code.Line("public override void Up(MigrationContext context)").Open();
            if (included.Count > 0) WriteGuard(code, dialect, id);
            else if (diff.Differences.Count == 0 && skipped.Count == 0) code.Line("// The entity types matched the database when this migration was generated.");

            foreach (MigrationOperation operation in included)
            {
                code.Blank();
                code.Line("// " + OneLine(operation.ToString()));
                if (operation.Warning != null) code.Line("// WARNING: " + OneLine(operation.Warning));
                foreach (SqlStatement statement in operation.Statements)
                    code.Line("context.ExecuteSqlRaw(" + CSharpNames.StringLiteral(statement.ToInlineSql(dialect)) + ");");
            }

            if (skipped.Count > 0)
            {
                code.Blank();
                code.Line("// Skipped destructive operations (run 'durable migrations add' with --allow-destructive to include them):");
                foreach (MigrationOperation operation in skipped) code.Line("//   " + OneLine(operation.Description));
            }

            if (diff.Differences.Count > 0)
            {
                code.Blank();
                code.Line("// Manual steps required (not generated):");
                foreach (SchemaDifference difference in diff.Differences) code.Line("//   " + OneLine(difference.Message));
            }

            code.Close();

            if (hasDown)
            {
                code.Blank();
                code.Summary("Reverts the migration.");
                code.Line("/// <param name=\"context\">Migration context.</param>");
                code.Line("/// <exception cref=\"NotSupportedException\">Thrown when the database is not " + CSharpNames.XmlEscape(databaseName) + ".</exception>");
                code.Line("public override void Down(MigrationContext context)").Open();
                WriteGuard(code, dialect, id);
                for (int i = included.Count - 1; i >= 0; i--)
                {
                    MigrationOperation operation = included[i];
                    code.Blank();
                    code.Line("// Revert: " + OneLine(operation.Description));
                    foreach (string sql in Reverse(dialect, operation)!) code.Line("context.ExecuteSqlRaw(" + CSharpNames.StringLiteral(sql) + ");");
                }

                code.Close();
            }
            else if (irreversible.Count > 0)
            {
                code.Blank();
                code.Line("// Down is not generated because these operations cannot be reversed automatically:");
                foreach (MigrationOperation operation in irreversible) code.Line("//   " + OneLine(operation.Description));
                code.Line("// Override Down(MigrationContext) by hand to make this migration reversible with 'durable rollback'.");
            }

            return End(code);
        }

        private static CodeWriter Begin(string namespaceName, string className, string id, string summary, bool usesGuard)
        {
            CodeWriter code = new CodeWriter();
            code.Line("namespace " + namespaceName).Open();
            if (usesGuard) code.Line("using System;");
            if (usesGuard) code.Line("using Durable;");
            code.Line("using Durable.Sql;");
            code.Blank();
            code.Summary(summary);
            code.Line("public class " + className + " : Migration").Open();
            code.Summary("Gets the migration identifier. Identifiers sort chronologically (UTC yyyyMMddHHmmss_Name).");
            code.Line("public override string Id => " + CSharpNames.StringLiteral(id) + ";");
            code.Blank();
            return code;
        }

        private static string End(CodeWriter code)
        {
            code.Close();
            code.Close();
            return code.ToString();
        }

        private static void WriteGuard(CodeWriter code, ISqlDialect dialect, string id)
        {
            string field = FieldName(dialect.RepositoryType);
            code.Line("if (context.Dialect.RepositoryType != RepositoryType." + field + ")");
            code.Line("    throw new NotSupportedException(" + CSharpNames.StringLiteral("Migration " + id + " was generated for " + dialect.RepositoryType.DisplayName + " and cannot run on ") +
                " + context.Dialect.RepositoryType.DisplayName + \".\");");
        }

        private static string FieldName(RepositoryType type)
        {
            if (type == RepositoryType.Sqlite) return nameof(RepositoryType.Sqlite);
            if (type == RepositoryType.DuckDb) return nameof(RepositoryType.DuckDb);
            if (type == RepositoryType.Postgres) return nameof(RepositoryType.Postgres);
            if (type == RepositoryType.MySql) return nameof(RepositoryType.MySql);
            if (type == RepositoryType.SqlServer) return nameof(RepositoryType.SqlServer);
            if (type == RepositoryType.Oracle) return nameof(RepositoryType.Oracle);
            throw new NotSupportedException("Migrations cannot be generated for " + type.DisplayName + ".");
        }

        private static List<string>? Reverse(ISqlDialect dialect, MigrationOperation operation)
        {
            switch (operation.Kind)
            {
                case MigrationOperationKind.CreateTable:
                    return new List<string> { "DROP TABLE " + dialect.QuoteIdentifier(operation.TableName) };
                case MigrationOperationKind.AddColumn:
                    if (operation.ColumnName == null || !dialect.SupportsDropColumn) return null;
                    return new List<string> { dialect.DropColumnSql(operation.TableName, operation.ColumnName) };
                case MigrationOperationKind.CreateIndex:
                    if (operation.IndexName == null) return null;
                    return new List<string> { dialect.DropIndexSql(operation.IndexName, operation.TableName) };
                default:
                    return null;
            }
        }

        private static string OneLine(string text)
        {
            return text.Replace("\r", " ", StringComparison.Ordinal).Replace("\n", " ", StringComparison.Ordinal);
        }
    }
}
