namespace Test.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Reflection;
    using Durable;
    using Durable.Sql;
    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.CSharp;
    using Microsoft.CodeAnalysis.Emit;

    /// <summary>
    /// Compiles C# generated by the durable tool in memory with Roslyn (nullable reference types enabled, XML documentation
    /// diagnostics on) and loads the result, so tests can prove generated code compiles cleanly and then execute it.
    /// </summary>
    public static class GeneratedCodeCompiler
    {
        private static readonly HashSet<string> _IgnoredWarnings = new HashSet<string>(StringComparer.Ordinal) { "CS1701", "CS1702" };

        /// <summary>
        /// Compiles sources into an assembly and loads it.
        /// </summary>
        /// <param name="assemblyName">Assembly name (unique per call). Must not be null.</param>
        /// <param name="sources">C# sources. Must not be null or empty.</param>
        /// <returns>The loaded assembly.</returns>
        /// <exception cref="InvalidOperationException">Thrown when compilation reports errors or warnings; the message lists them with the sources.</exception>
        public static Assembly CompileAndLoad(string assemblyName, IReadOnlyList<string> sources)
        {
            ArgumentNullException.ThrowIfNull(assemblyName);
            ArgumentNullException.ThrowIfNull(sources);
            if (sources.Count == 0) throw new ArgumentException("At least one source is required.", nameof(sources));

            CSharpParseOptions parseOptions = new CSharpParseOptions(LanguageVersion.CSharp12, DocumentationMode.Diagnose);
            List<SyntaxTree> trees = sources.Select((s, i) => CSharpSyntaxTree.ParseText(s, parseOptions, "Generated" + i + ".cs")).ToList();
            CSharpCompilation compilation = CSharpCompilation.Create(
                assemblyName,
                trees,
                References(),
                new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary, nullableContextOptions: NullableContextOptions.Enable));

            using MemoryStream image = new MemoryStream();
            using MemoryStream documentation = new MemoryStream();
            EmitResult result = compilation.Emit(image, xmlDocumentationStream: documentation);
            List<Diagnostic> problems = result.Diagnostics
                .Where(d => d.Severity == DiagnosticSeverity.Error || (d.Severity == DiagnosticSeverity.Warning && !_IgnoredWarnings.Contains(d.Id)))
                .ToList();
            if (!result.Success || problems.Count > 0)
            {
                throw new InvalidOperationException(
                    "Generated code did not compile cleanly:\n" + string.Join("\n", problems.Select(p => p.ToString())) + "\n\n" + string.Join("\n// ----\n", sources));
            }

            return Assembly.Load(image.ToArray());
        }

        private static List<MetadataReference> References()
        {
            Dictionary<string, string> paths = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            string? platform = AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES") as string;
            if (platform != null)
            {
                foreach (string path in platform.Split(Path.PathSeparator).Where(p => p.EndsWith(".dll", StringComparison.OrdinalIgnoreCase)))
                    paths[Path.GetFileName(path)] = path;
            }

            foreach (Assembly assembly in new[] { typeof(object).Assembly, typeof(EntityAttribute).Assembly, typeof(Migration).Assembly })
                paths[Path.GetFileName(assembly.Location)] = assembly.Location;
            return paths.Values.Select(p => (MetadataReference)MetadataReference.CreateFromFile(p)).ToList();
        }
    }
}
