<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net10.0</TargetFrameworks>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<NoWarn>$(NoWarn);CS1591;CS1573</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
		<PackageReference Include="MySqlConnector" Version="2.6.2" />
		<PackageReference Include="Npgsql" Version="10.0.3" />
		<PackageReference Include="Touchstone.Core" Version="0.1.12" />
		<PackageReference Include="xunit.assert" Version="2.9.3" />
		<PackageReference Include="xunit.extensibility.core" Version="2.9.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Durable\Durable.csproj" />
		<ProjectReference Include="..\..\src\Durable.Conformance\Durable.Conformance.csproj" />
		<ProjectReference Include="..\..\src\Durable.InMemory\Durable.InMemory.csproj" />
		<ProjectReference Include="..\..\src\Durable.Sqlite\Durable.Sqlite.csproj" />
		<ProjectReference Include="..\..\src\Durable.MySql\Durable.MySql.csproj" />
		<ProjectReference Include="..\..\src\Durable.Postgres\Durable.Postgres.csproj" />
		<ProjectReference Include="..\..\src\Durable.SqlServer\Durable.SqlServer.csproj" />
	</ItemGroup>

</Project>
