namespace Durable
{
    /// <summary>
    /// Specifies the type of built-in default value to generate for a property
    /// </summary>
    public enum DefaultValueType
    {
        /// <summary>
        /// No default value
        /// </summary>
        None = 0,

        /// <summary>
        /// Current UTC date and time (DateTime.UtcNow)
        /// </summary>
        CurrentDateTimeUtc = 1,

        /// <summary>
        /// Current local date and time (DateTime.Now)
        /// </summary>
        CurrentDateTimeLocal = 2,

        /// <summary>
        /// New globally unique identifier (Guid.NewGuid())
        /// </summary>
        NewGuid = 3,

        /// <summary>
        /// Empty GUID (Guid.Empty)
        /// </summary>
        EmptyGuid = 4,

        /// <summary>
        /// Empty string (string.Empty)
        /// </summary>
        EmptyString = 5,

        /// <summary>
        /// Zero value (0 for numeric types)
        /// </summary>
        Zero = 6,

        /// <summary>
        /// A static value specified in the attribute
        /// </summary>
        StaticValue = 7,

        /// <summary>
        /// Value generated by a custom provider
        /// </summary>
        CustomProvider = 8,

        /// <summary>
        /// New sequential GUID optimized for database indexing
        /// </summary>
        SequentialGuid = 9,

        /// <summary>
        /// Current date only (no time component) in UTC
        /// </summary>
        CurrentDateUtc = 10,

        /// <summary>
        /// Current date only (no time component) in local time
        /// </summary>
        CurrentDateLocal = 11,

        /// <summary>
        /// True boolean value
        /// </summary>
        True = 12,

        /// <summary>
        /// False boolean value
        /// </summary>
        False = 13
    }
}
