namespace Durable
{
    using System;

    /// <summary>
    /// Column flags that refine how a mapped property is stored and treated by a repository.
    /// Flags may be combined with the bitwise OR operator.
    /// </summary>
    [Flags]
    public enum Flags
    {
        /// <summary>
        /// No special treatment.
        /// </summary>
        None = 0,

        /// <summary>
        /// The column is part of the primary key. Multiple properties may carry this flag to form a composite key;
        /// order them with <see cref="PropertyAttribute.KeyOrder"/>.
        /// </summary>
        PrimaryKey = 1,

        /// <summary>
        /// The column is stored as a string. For enums this is the default; the flag is retained for explicitness.
        /// </summary>
        String = 2,

        /// <summary>
        /// The column value is generated by the database on insert (identity / auto-increment).
        /// </summary>
        AutoIncrement = 4,

        /// <summary>
        /// For enum properties, store the underlying integer value instead of the enum name.
        /// </summary>
        Integer = 8,

        /// <summary>
        /// Store the property value serialized as JSON. Collections and complex objects are stored as JSON implicitly;
        /// this flag makes the intent explicit and allows providers to use a native JSON column type.
        /// </summary>
        Json = 16
    }
}
